# encoding: UTF-8
# This file is auto-generated from the current state of the database. Instead
# of editing this file, please use the migrations feature of Active Record to
# incrementally modify your database, and then regenerate this schema definition.
#
# Note that this schema.rb definition is the authoritative source for your
# database schema. If you need to create the application database on another
# system, you should be using db:schema:load, not running all the migrations
# from scratch. The latter is a flawed and unsustainable approach (the more migrations
# you'll amass, the slower it'll run and the greater likelihood for issues).
#
# It's strongly recommended that you check this file into your version control system.

ActiveRecord::Schema.define(version: 20130911225844) do

  create_table "datafeed_old", force: true do |t|
    t.string   "accept_language",        limit: 11
    t.integer  "browser"
    t.integer  "connection_type"
    t.integer  "country"
    t.datetime "date_time"
    t.string   "domain",                 limit: 50
    t.string   "evar1"
    t.string   "evar2"
    t.string   "evar3"
    t.string   "evar4"
    t.string   "evar5"
    t.string   "evar6"
    t.string   "evar7"
    t.string   "evar8"
    t.string   "evar9"
    t.string   "evar10"
    t.string   "evar11"
    t.string   "evar12"
    t.string   "evar13"
    t.string   "evar14"
    t.string   "evar15"
    t.string   "evar16"
    t.string   "evar17"
    t.string   "evar18"
    t.string   "evar19"
    t.string   "evar20"
    t.string   "evar21"
    t.string   "evar22"
    t.string   "evar23"
    t.string   "evar24"
    t.string   "evar25"
    t.string   "evar26"
    t.string   "evar27"
    t.string   "evar28"
    t.string   "evar29"
    t.string   "evar30"
    t.string   "evar31"
    t.string   "evar32"
    t.string   "evar33"
    t.string   "evar34"
    t.string   "evar35"
    t.string   "evar36"
    t.string   "evar37"
    t.string   "evar38"
    t.string   "evar39"
    t.string   "evar40"
    t.string   "evar41"
    t.string   "evar42"
    t.string   "evar43"
    t.string   "evar44"
    t.string   "evar45"
    t.string   "evar46"
    t.string   "evar47"
    t.string   "evar48"
    t.string   "evar49"
    t.string   "evar50"
    t.string   "evar51"
    t.string   "evar52"
    t.string   "evar53"
    t.string   "evar54"
    t.string   "evar55"
    t.string   "evar56"
    t.string   "evar57"
    t.string   "evar58"
    t.string   "evar59"
    t.string   "evar60"
    t.string   "evar61"
    t.string   "evar62"
    t.string   "evar63"
    t.string   "evar64"
    t.string   "evar65"
    t.string   "evar66"
    t.string   "evar67"
    t.string   "evar68"
    t.string   "evar69"
    t.string   "evar70"
    t.string   "evar71"
    t.string   "evar72"
    t.string   "evar73"
    t.string   "evar74"
    t.string   "evar75"
    t.string   "exclude_hit",            limit: 11
    t.string   "first_hit_pagename",     limit: 11
    t.string   "first_hit_page_url",     limit: 11
    t.string   "first_hit_referrer",     limit: 11
    t.datetime "first_hit_time_gmt"
    t.string   "geo_city",               limit: 11
    t.string   "geo_country",            limit: 11
    t.string   "geo_dma",                limit: 11
    t.string   "geo_region",             limit: 11
    t.string   "geo_zip",                limit: 11
    t.string   "ip",                     limit: 11
    t.string   "javascript",             limit: 11
    t.string   "language",               limit: 11
    t.datetime "last_hit_time_gmt"
    t.string   "last_purchase_num",      limit: 11
    t.datetime "last_purchase_time_gmt"
    t.string   "new_visit",              limit: 11
    t.string   "os",                     limit: 11
    t.string   "post_browser_height",    limit: 11
    t.string   "post_browser_width",     limit: 11
    t.string   "post_campaign"
    t.string   "post_channel"
    t.string   "post_cookies",           limit: 50
    t.string   "post_currency",          limit: 11
    t.datetime "post_cust_hit_time_gmt"
    t.string   "post_evar1"
    t.string   "post_evar2"
    t.string   "post_evar3"
    t.string   "post_evar4"
    t.string   "post_evar5"
    t.string   "post_evar6"
    t.string   "post_evar7"
    t.string   "post_evar8"
    t.string   "post_evar9"
    t.string   "post_evar10"
    t.string   "post_evar11"
    t.string   "post_evar12"
    t.string   "post_evar13"
    t.string   "post_evar14"
    t.string   "post_evar15"
    t.string   "post_evar16"
    t.string   "post_evar17"
    t.string   "post_evar18"
    t.string   "post_evar19"
    t.string   "post_evar20"
    t.string   "post_evar21"
    t.string   "post_evar22"
    t.string   "post_evar23"
    t.string   "post_evar24"
    t.string   "post_evar25"
    t.string   "post_evar26"
    t.string   "post_evar27"
    t.string   "post_evar28"
    t.string   "post_evar29"
    t.string   "post_evar30"
    t.string   "post_evar31"
    t.string   "post_evar32"
    t.string   "post_evar33"
    t.string   "post_evar34"
    t.string   "post_evar35"
    t.string   "post_evar36"
    t.string   "post_evar37"
    t.string   "post_evar38"
    t.string   "post_evar39"
    t.string   "post_evar40"
    t.string   "post_evar41"
    t.string   "post_evar42"
    t.string   "post_evar43"
    t.string   "post_evar44"
    t.string   "post_evar45"
    t.string   "post_evar46"
    t.string   "post_evar47"
    t.string   "post_evar48"
    t.string   "post_evar49"
    t.string   "post_evar50"
    t.string   "post_evar51"
    t.string   "post_evar52"
    t.string   "post_evar53"
    t.string   "post_evar54"
    t.string   "post_evar55"
    t.string   "post_evar56"
    t.string   "post_evar57"
    t.string   "post_evar58"
    t.string   "post_evar59"
    t.string   "post_evar60"
    t.string   "post_evar61"
    t.string   "post_evar62"
    t.string   "post_evar63"
    t.string   "post_evar64"
    t.string   "post_evar65"
    t.string   "post_evar66"
    t.string   "post_evar67"
    t.string   "post_evar68"
    t.string   "post_evar69"
    t.string   "post_evar70"
    t.string   "post_evar71"
    t.string   "post_evar72"
    t.string   "post_evar73"
    t.string   "post_evar74"
    t.string   "post_evar75"
    t.string   "post_event_list"
    t.string   "post_hier1"
    t.string   "post_hier2"
    t.string   "post_hier3"
    t.string   "post_hier4"
    t.string   "post_hier5"
    t.string   "post_keywords"
    t.string   "post_page_event"
    t.string   "post_page_event_var1"
    t.string   "post_page_event_var2"
    t.string   "post_page_event_var3"
    t.string   "post_pagename"
    t.string   "post_pagename_no_url"
    t.string   "post_page_type"
    t.string   "post_page_url"
    t.string   "post_persistent_cookie"
    t.string   "post_product_list"
    t.string   "post_prop1"
    t.string   "post_prop2"
    t.string   "post_prop3"
    t.string   "post_prop4"
    t.string   "post_prop5"
    t.string   "post_prop6"
    t.string   "post_prop7"
    t.string   "post_prop8"
    t.string   "post_prop9"
    t.string   "post_prop10"
    t.string   "post_prop11"
    t.string   "post_prop12"
    t.string   "post_prop13"
    t.string   "post_prop14"
    t.string   "post_prop15"
    t.string   "post_prop16"
    t.string   "post_prop17"
    t.string   "post_prop18"
    t.string   "post_prop19"
    t.string   "post_prop20"
    t.string   "post_prop21"
    t.string   "post_prop22"
    t.string   "post_prop23"
    t.string   "post_prop24"
    t.string   "post_prop25"
    t.string   "post_prop26"
    t.string   "post_prop27"
    t.string   "post_prop28"
    t.string   "post_prop29"
    t.string   "post_prop30"
    t.string   "post_prop31"
    t.string   "post_prop32"
    t.string   "post_prop33"
    t.string   "post_prop34"
    t.string   "post_prop35"
    t.string   "post_prop36"
    t.string   "post_prop37"
    t.string   "post_prop38"
    t.string   "post_prop39"
    t.string   "post_prop40"
    t.string   "post_prop41"
    t.string   "post_prop42"
    t.string   "post_prop43"
    t.string   "post_prop44"
    t.string   "post_prop45"
    t.string   "post_prop46"
    t.string   "post_prop47"
    t.string   "post_prop48"
    t.string   "post_prop49"
    t.string   "post_prop50"
    t.string   "post_prop51"
    t.string   "post_prop52"
    t.string   "post_prop53"
    t.string   "post_prop54"
    t.string   "post_prop55"
    t.string   "post_prop56"
    t.string   "post_prop57"
    t.string   "post_prop58"
    t.string   "post_prop59"
    t.string   "post_prop60"
    t.string   "post_prop61"
    t.string   "post_prop62"
    t.string   "post_prop63"
    t.string   "post_prop64"
    t.string   "post_prop65"
    t.string   "post_prop66"
    t.string   "post_prop67"
    t.string   "post_prop68"
    t.string   "post_prop69"
    t.string   "post_prop70"
    t.string   "post_prop71"
    t.string   "post_prop72"
    t.string   "post_prop73"
    t.string   "post_prop74"
    t.string   "post_prop75"
    t.string   "post_purchaseid",        limit: 50
    t.string   "post_referrer"
    t.string   "post_search_engine",     limit: 50
    t.string   "post_state",             limit: 11
    t.string   "post_visid_high",        limit: 50
    t.string   "post_visid_low",         limit: 50
    t.string   "post_zip",               limit: 11
    t.string   "prev_page"
    t.string   "ref_domain"
    t.string   "ref_type",               limit: 50
    t.string   "resolution",             limit: 50
    t.string   "service",                limit: 50
    t.string   "user_agent"
    t.string   "visit_keywords"
    t.string   "visit_num",              limit: 11
    t.string   "visit_page_num",         limit: 11
    t.string   "visit_referrer"
    t.string   "visit_search_engine"
    t.string   "visit_start_pagename"
    t.string   "visit_start_page_url",   limit: 11
    t.datetime "visit_start_time_gmt"
  end

  create_table "datafeeds", force: true do |t|
    t.text     "accept_language"
    t.text     "browser"
    t.text     "browser_height"
    t.text     "browser_width"
    t.text     "campaign"
    t.text     "channel"
    t.text     "click_action"
    t.text     "click_action_type"
    t.text     "click_context_type"
    t.text     "click_sourceid"
    t.text     "click_tag"
    t.text     "color"
    t.text     "connection_type"
    t.text     "cookies"
    t.text     "country"
    t.text     "ct_connect_type"
    t.text     "currency"
    t.text     "curr_factor"
    t.text     "curr_rate"
    t.text     "cust_hit_time_gmt"
    t.text     "cust_visid"
    t.text     "daily_visitor"
    t.datetime "date_time"
    t.text     "domain"
    t.text     "duplicated_from"
    t.text     "duplicate_events"
    t.text     "duplicate_purchase"
    t.text     "evar1"
    t.text     "evar2"
    t.text     "evar3"
    t.text     "evar4"
    t.text     "evar5"
    t.text     "evar6"
    t.text     "evar7"
    t.text     "evar8"
    t.text     "evar9"
    t.text     "evar10"
    t.text     "evar11"
    t.text     "evar12"
    t.text     "evar13"
    t.text     "evar14"
    t.text     "evar15"
    t.text     "evar16"
    t.text     "evar17"
    t.text     "evar18"
    t.text     "evar19"
    t.text     "evar20"
    t.text     "evar21"
    t.text     "evar22"
    t.text     "evar23"
    t.text     "evar24"
    t.text     "evar25"
    t.text     "evar26"
    t.text     "evar27"
    t.text     "evar28"
    t.text     "evar29"
    t.text     "evar30"
    t.text     "evar31"
    t.text     "evar32"
    t.text     "evar33"
    t.text     "evar34"
    t.text     "evar35"
    t.text     "evar36"
    t.text     "evar37"
    t.text     "evar38"
    t.text     "evar39"
    t.text     "evar40"
    t.text     "evar41"
    t.text     "evar42"
    t.text     "evar43"
    t.text     "evar44"
    t.text     "evar45"
    t.text     "evar46"
    t.text     "evar47"
    t.text     "evar48"
    t.text     "evar49"
    t.text     "evar50"
    t.text     "evar51"
    t.text     "evar52"
    t.text     "evar53"
    t.text     "evar54"
    t.text     "evar55"
    t.text     "evar56"
    t.text     "evar57"
    t.text     "evar58"
    t.text     "evar59"
    t.text     "evar60"
    t.text     "evar61"
    t.text     "evar62"
    t.text     "evar63"
    t.text     "evar64"
    t.text     "evar65"
    t.text     "evar66"
    t.text     "evar67"
    t.text     "evar68"
    t.text     "evar69"
    t.text     "evar70"
    t.text     "evar71"
    t.text     "evar72"
    t.text     "evar73"
    t.text     "evar74"
    t.text     "evar75"
    t.text     "event_list"
    t.text     "exclude_hit"
    t.text     "first_hit_pagename"
    t.text     "first_hit_page_url"
    t.text     "first_hit_referrer"
    t.text     "first_hit_time_gmt"
    t.text     "geo_city"
    t.text     "geo_country"
    t.text     "geo_dma"
    t.text     "geo_region"
    t.text     "geo_zip"
    t.text     "hier1"
    t.text     "hier2"
    t.text     "hier3"
    t.text     "hier4"
    t.text     "hier5"
    t.text     "hitid_low"
    t.text     "hit_source"
    t.text     "hit_time_gmt"
    t.text     "homepage"
    t.text     "hourly_visitor"
    t.text     "ip"
    t.text     "ip2"
    t.text     "java_enabled"
    t.text     "javascript"
    t.text     "j_jscript"
    t.text     "language"
    t.text     "last_hit_time_gmt"
    t.text     "last_purchase_num"
    t.text     "last_purchase_time_gmt"
    t.text     "mobile_id"
    t.text     "monthly_visitor"
    t.text     "mvvar1"
    t.text     "mvvar2"
    t.text     "mvvar3"
    t.text     "namespace"
    t.text     "new_visit"
    t.text     "os"
    t.text     "page_event"
    t.text     "page_event_var1"
    t.text     "page_event_var2"
    t.text     "pagename"
    t.text     "page_type"
    t.text     "paid_search"
    t.text     "persistent_cookie"
    t.text     "plugins"
    t.text     "post_browser_height"
    t.text     "post_browser_width"
    t.text     "post_campaign"
    t.text     "post_channel"
    t.text     "post_cookies"
    t.text     "post_currency"
    t.text     "post_cust_hit_time_gmt"
    t.text     "post_cust_visid"
    t.text     "post_evar1"
    t.text     "post_evar2"
    t.text     "post_evar3"
    t.text     "post_evar4"
    t.text     "post_evar5"
    t.text     "post_evar6"
    t.text     "post_evar7"
    t.text     "post_evar8"
    t.text     "post_evar9"
    t.text     "post_evar10"
    t.text     "post_evar11"
    t.text     "post_evar12"
    t.text     "post_evar13"
    t.text     "post_evar14"
    t.text     "post_evar15"
    t.text     "post_evar16"
    t.text     "post_evar17"
    t.text     "post_evar18"
    t.text     "post_evar19"
    t.text     "post_evar20"
    t.text     "post_evar21"
    t.text     "post_evar22"
    t.text     "post_evar23"
    t.text     "post_evar24"
    t.text     "post_evar25"
    t.text     "post_evar26"
    t.text     "post_evar27"
    t.text     "post_evar28"
    t.text     "post_evar29"
    t.text     "post_evar30"
    t.text     "post_evar31"
    t.text     "post_evar32"
    t.text     "post_evar33"
    t.text     "post_evar34"
    t.text     "post_evar35"
    t.text     "post_evar36"
    t.text     "post_evar37"
    t.text     "post_evar38"
    t.text     "post_evar39"
    t.text     "post_evar40"
    t.text     "post_evar41"
    t.text     "post_evar42"
    t.text     "post_evar43"
    t.text     "post_evar44"
    t.text     "post_evar45"
    t.text     "post_evar46"
    t.text     "post_evar47"
    t.text     "post_evar48"
    t.text     "post_evar49"
    t.text     "post_evar50"
    t.text     "post_evar51"
    t.text     "post_evar52"
    t.text     "post_evar53"
    t.text     "post_evar54"
    t.text     "post_evar55"
    t.text     "post_evar56"
    t.text     "post_evar57"
    t.text     "post_evar58"
    t.text     "post_evar59"
    t.text     "post_evar60"
    t.text     "post_evar61"
    t.text     "post_evar62"
    t.text     "post_evar63"
    t.text     "post_evar64"
    t.text     "post_evar65"
    t.text     "post_evar66"
    t.text     "post_evar67"
    t.text     "post_evar68"
    t.text     "post_evar69"
    t.text     "post_evar70"
    t.text     "post_evar71"
    t.text     "post_evar72"
    t.text     "post_evar73"
    t.text     "post_evar74"
    t.text     "post_evar75"
    t.text     "post_event_list"
    t.text     "post_hier1"
    t.text     "post_hier2"
    t.text     "post_hier3"
    t.text     "post_hier4"
    t.text     "post_hier5"
    t.text     "post_java_enabled"
    t.text     "post_keywords"
    t.text     "post_mvvar1"
    t.text     "post_mvvar2"
    t.text     "post_mvvar3"
    t.text     "post_page_event"
    t.text     "post_page_event_var1"
    t.text     "post_page_event_var2"
    t.text     "post_page_event_var3"
    t.text     "post_pagename"
    t.text     "post_pagename_no_url"
    t.text     "post_page_type"
    t.text     "post_page_url"
    t.text     "post_partner_plugins"
    t.text     "post_persistent_cookie"
    t.text     "post_product_list"
    t.text     "post_prop1"
    t.text     "post_prop2"
    t.text     "post_prop3"
    t.text     "post_prop4"
    t.text     "post_prop5"
    t.text     "post_prop6"
    t.text     "post_prop7"
    t.text     "post_prop8"
    t.text     "post_prop9"
    t.text     "post_prop10"
    t.text     "post_prop11"
    t.text     "post_prop12"
    t.text     "post_prop13"
    t.text     "post_prop14"
    t.text     "post_prop15"
    t.text     "post_prop16"
    t.text     "post_prop17"
    t.text     "post_prop18"
    t.text     "post_prop19"
    t.text     "post_prop20"
    t.text     "post_prop21"
    t.text     "post_prop22"
    t.text     "post_prop23"
    t.text     "post_prop24"
    t.text     "post_prop25"
    t.text     "post_prop26"
    t.text     "post_prop27"
    t.text     "post_prop28"
    t.text     "post_prop29"
    t.text     "post_prop30"
    t.text     "post_prop31"
    t.text     "post_prop32"
    t.text     "post_prop33"
    t.text     "post_prop34"
    t.text     "post_prop35"
    t.text     "post_prop36"
    t.text     "post_prop37"
    t.text     "post_prop38"
    t.text     "post_prop39"
    t.text     "post_prop40"
    t.text     "post_prop41"
    t.text     "post_prop42"
    t.text     "post_prop43"
    t.text     "post_prop44"
    t.text     "post_prop45"
    t.text     "post_prop46"
    t.text     "post_prop47"
    t.text     "post_prop48"
    t.text     "post_prop49"
    t.text     "post_prop50"
    t.text     "post_prop51"
    t.text     "post_prop52"
    t.text     "post_prop53"
    t.text     "post_prop54"
    t.text     "post_prop55"
    t.text     "post_prop56"
    t.text     "post_prop57"
    t.text     "post_prop58"
    t.text     "post_prop59"
    t.text     "post_prop60"
    t.text     "post_prop61"
    t.text     "post_prop62"
    t.text     "post_prop63"
    t.text     "post_prop64"
    t.text     "post_prop65"
    t.text     "post_prop66"
    t.text     "post_prop67"
    t.text     "post_prop68"
    t.text     "post_prop69"
    t.text     "post_prop70"
    t.text     "post_prop71"
    t.text     "post_prop72"
    t.text     "post_prop73"
    t.text     "post_prop74"
    t.text     "post_prop75"
    t.text     "post_purchaseid"
    t.text     "post_referrer"
    t.text     "post_search_engine"
    t.text     "post_state"
    t.text     "post_survey"
    t.text     "post_tnt"
    t.text     "post_transactionid"
    t.text     "post_t_time_info"
    t.text     "post_visid_high"
    t.text     "post_visid_low"
    t.text     "post_visid_type"
    t.text     "post_zip"
    t.text     "p_plugins"
    t.text     "prev_page"
    t.text     "product_list"
    t.text     "product_merchandising"
    t.text     "prop1"
    t.text     "prop2"
    t.text     "prop3"
    t.text     "prop4"
    t.text     "prop5"
    t.text     "prop6"
    t.text     "prop7"
    t.text     "prop8"
    t.text     "prop9"
    t.text     "prop10"
    t.text     "prop11"
    t.text     "prop12"
    t.text     "prop13"
    t.text     "prop14"
    t.text     "prop15"
    t.text     "prop16"
    t.text     "prop17"
    t.text     "prop18"
    t.text     "prop19"
    t.text     "prop20"
    t.text     "prop21"
    t.text     "prop22"
    t.text     "prop23"
    t.text     "prop24"
    t.text     "prop25"
    t.text     "prop26"
    t.text     "prop27"
    t.text     "prop28"
    t.text     "prop29"
    t.text     "prop30"
    t.text     "prop31"
    t.text     "prop32"
    t.text     "prop33"
    t.text     "prop34"
    t.text     "prop35"
    t.text     "prop36"
    t.text     "prop37"
    t.text     "prop38"
    t.text     "prop39"
    t.text     "prop40"
    t.text     "prop41"
    t.text     "prop42"
    t.text     "prop43"
    t.text     "prop44"
    t.text     "prop45"
    t.text     "prop46"
    t.text     "prop47"
    t.text     "prop48"
    t.text     "prop49"
    t.text     "prop50"
    t.text     "prop51"
    t.text     "prop52"
    t.text     "prop53"
    t.text     "prop54"
    t.text     "prop55"
    t.text     "prop56"
    t.text     "prop57"
    t.text     "prop58"
    t.text     "prop59"
    t.text     "prop60"
    t.text     "prop61"
    t.text     "prop62"
    t.text     "prop63"
    t.text     "prop64"
    t.text     "prop65"
    t.text     "prop66"
    t.text     "prop67"
    t.text     "prop68"
    t.text     "prop69"
    t.text     "prop70"
    t.text     "prop71"
    t.text     "prop72"
    t.text     "prop73"
    t.text     "prop74"
    t.text     "prop75"
    t.text     "purchaseid"
    t.text     "quarterly_visitor"
    t.text     "ref_domain"
    t.text     "referrer"
    t.text     "ref_type"
    t.text     "resolution"
    t.text     "sampled_hit"
    t.text     "search_engine"
    t.text     "search_page_num"
    t.text     "secondary_hit"
    t.text     "service"
    t.text     "sourceid"
    t.text     "s_resolution"
    t.text     "state"
    t.text     "stats_server"
    t.text     "tnt"
    t.text     "tnt_post_vista"
    t.text     "transactionid"
    t.text     "truncated_hit"
    t.text     "t_time_info"
    t.text     "ua_color"
    t.text     "ua_os"
    t.text     "ua_pixels"
    t.text     "user_agent"
    t.text     "user_hash"
    t.text     "userid"
    t.text     "username"
    t.text     "user_server"
    t.text     "va_closer_id"
    t.text     "va_finder_detail"
    t.text     "va_finder_id"
    t.text     "va_instance_event"
    t.text     "va_new_engagement"
    t.text     "visid_high"
    t.text     "visid_low"
    t.text     "visid_new"
    t.text     "visid_timestamp"
    t.text     "visid_type"
    t.text     "visit_keywords"
    t.text     "visit_num"
    t.text     "visit_page_num"
    t.text     "visit_referrer"
    t.text     "visit_search_engine"
    t.text     "visit_start_pagename"
    t.text     "visit_start_page_url"
    t.text     "visit_start_time_gmt"
    t.text     "weekly_visitor"
    t.text     "yearly_visitor"
    t.text     "zip"
    t.datetime "created_at"
    t.datetime "updated_at"
    t.text     "c_color"
    t.text     "click_context"
    t.text     "code_ver"
    t.text     "hitid_high"
    t.text     "partner_plugins"
    t.text     "page_event_var3"
    t.text     "va_closer_detail"
    t.text     "page_url"
  end

  create_table "datafeeds_2", force: true do |t|
    t.text     "accept_language"
    t.text     "browser"
    t.text     "connection_type"
    t.text     "country"
    t.datetime "date_time"
    t.text     "domain"
    t.text     "evar1"
    t.text     "evar2"
    t.text     "evar3"
    t.text     "evar4"
    t.text     "evar5"
    t.text     "evar6"
    t.text     "evar7"
    t.text     "evar8"
    t.text     "evar9"
    t.text     "evar10"
    t.text     "evar11"
    t.text     "evar12"
    t.text     "evar13"
    t.text     "evar14"
    t.text     "evar15"
    t.text     "evar16"
    t.text     "evar17"
    t.text     "evar18"
    t.text     "evar19"
    t.text     "evar20"
    t.text     "evar21"
    t.text     "evar22"
    t.text     "evar23"
    t.text     "evar24"
    t.text     "evar25"
    t.text     "evar26"
    t.text     "evar27"
    t.text     "evar28"
    t.text     "evar29"
    t.text     "evar30"
    t.text     "evar31"
    t.text     "evar32"
    t.text     "evar33"
    t.text     "evar34"
    t.text     "evar35"
    t.text     "evar36"
    t.text     "evar37"
    t.text     "evar38"
    t.text     "evar39"
    t.text     "evar40"
    t.text     "evar41"
    t.text     "evar42"
    t.text     "evar43"
    t.text     "evar44"
    t.text     "evar45"
    t.text     "evar46"
    t.text     "evar47"
    t.text     "evar48"
    t.text     "evar49"
    t.text     "evar50"
    t.text     "evar51"
    t.text     "evar52"
    t.text     "evar53"
    t.text     "evar54"
    t.text     "evar55"
    t.text     "evar56"
    t.text     "evar57"
    t.text     "evar58"
    t.text     "evar59"
    t.text     "evar60"
    t.text     "evar61"
    t.text     "evar62"
    t.text     "evar63"
    t.text     "evar64"
    t.text     "evar65"
    t.text     "evar66"
    t.text     "evar67"
    t.text     "evar68"
    t.text     "evar69"
    t.text     "evar70"
    t.text     "evar71"
    t.text     "evar72"
    t.text     "evar73"
    t.text     "evar74"
    t.text     "evar75"
    t.text     "exclude_hit"
    t.text     "first_hit_pagename"
    t.text     "first_hit_page_url"
    t.text     "first_hit_referrer"
    t.datetime "first_hit_time_gmt"
    t.text     "geo_city"
    t.text     "geo_country"
    t.text     "geo_dma"
    t.text     "geo_region"
    t.text     "geo_zip"
    t.text     "ip"
    t.text     "javascript"
    t.text     "language"
    t.datetime "last_hit_time_gmt"
    t.text     "last_purchase_num"
    t.text     "last_purchase_time_gmt"
    t.text     "new_visit"
    t.text     "os"
    t.text     "post_browser_height"
    t.text     "post_browser_width"
    t.text     "post_campaign"
    t.text     "post_channel"
    t.text     "post_cookies"
    t.text     "post_currency"
    t.datetime "post_cust_hit_time_gmt"
    t.text     "post_evar1"
    t.text     "post_evar2"
    t.text     "post_evar3"
    t.text     "post_evar4"
    t.text     "post_evar5"
    t.text     "post_evar6"
    t.text     "post_evar7"
    t.text     "post_evar8"
    t.text     "post_evar9"
    t.text     "post_evar10"
    t.text     "post_evar11"
    t.text     "post_evar12"
    t.text     "post_evar13"
    t.text     "post_evar14"
    t.text     "post_evar15"
    t.text     "post_evar16"
    t.text     "post_evar17"
    t.text     "post_evar18"
    t.text     "post_evar19"
    t.text     "post_evar20"
    t.text     "post_evar21"
    t.text     "post_evar22"
    t.text     "post_evar23"
    t.text     "post_evar24"
    t.text     "post_evar25"
    t.text     "post_evar26"
    t.text     "post_evar27"
    t.text     "post_evar28"
    t.text     "post_evar29"
    t.text     "post_evar30"
    t.text     "post_evar31"
    t.text     "post_evar32"
    t.text     "post_evar33"
    t.text     "post_evar34"
    t.text     "post_evar35"
    t.text     "post_evar36"
    t.text     "post_evar37"
    t.text     "post_evar38"
    t.text     "post_evar39"
    t.text     "post_evar40"
    t.text     "post_evar41"
    t.text     "post_evar42"
    t.text     "post_evar43"
    t.text     "post_evar44"
    t.text     "post_evar45"
    t.text     "post_evar46"
    t.text     "post_evar47"
    t.text     "post_evar48"
    t.text     "post_evar49"
    t.text     "post_evar50"
    t.text     "post_evar51"
    t.text     "post_evar52"
    t.text     "post_evar53"
    t.text     "post_evar54"
    t.text     "post_evar55"
    t.text     "post_evar56"
    t.text     "post_evar57"
    t.text     "post_evar58"
    t.text     "post_evar59"
    t.text     "post_evar60"
    t.text     "post_evar61"
    t.text     "post_evar62"
    t.text     "post_evar63"
    t.text     "post_evar64"
    t.text     "post_evar65"
    t.text     "post_evar66"
    t.text     "post_evar67"
    t.text     "post_evar68"
    t.text     "post_evar69"
    t.text     "post_evar70"
    t.text     "post_evar71"
    t.text     "post_evar72"
    t.text     "post_evar73"
    t.text     "post_evar74"
    t.text     "post_evar75"
    t.text     "post_event_list"
    t.text     "post_hier1"
    t.text     "post_hier2"
    t.text     "post_hier3"
    t.text     "post_hier4"
    t.text     "post_hier5"
    t.text     "post_keywords"
    t.text     "post_page_event"
    t.text     "post_page_event_var1"
    t.text     "post_page_event_var2"
    t.text     "post_page_event_var3"
    t.text     "post_pagename"
    t.text     "post_pagename_no_url"
    t.text     "post_page_type"
    t.text     "post_page_url"
    t.text     "post_persistent_cookie"
    t.text     "post_product_list"
    t.text     "post_prop1"
    t.text     "post_prop2"
    t.text     "post_prop3"
    t.text     "post_prop4"
    t.text     "post_prop5"
    t.text     "post_prop6"
    t.text     "post_prop7"
    t.text     "post_prop8"
    t.text     "post_prop9"
    t.text     "post_prop10"
    t.text     "post_prop11"
    t.text     "post_prop12"
    t.text     "post_prop13"
    t.text     "post_prop14"
    t.text     "post_prop15"
    t.text     "post_prop16"
    t.text     "post_prop17"
    t.text     "post_prop18"
    t.text     "post_prop19"
    t.text     "post_prop20"
    t.text     "post_prop21"
    t.text     "post_prop22"
    t.text     "post_prop23"
    t.text     "post_prop24"
    t.text     "post_prop25"
    t.text     "post_prop26"
    t.text     "post_prop27"
    t.text     "post_prop28"
    t.text     "post_prop29"
    t.text     "post_prop30"
    t.text     "post_prop31"
    t.text     "post_prop32"
    t.text     "post_prop33"
    t.text     "post_prop34"
    t.text     "post_prop35"
    t.text     "post_prop36"
    t.text     "post_prop37"
    t.text     "post_prop38"
    t.text     "post_prop39"
    t.text     "post_prop40"
    t.text     "post_prop41"
    t.text     "post_prop42"
    t.text     "post_prop43"
    t.text     "post_prop44"
    t.text     "post_prop45"
    t.text     "post_prop46"
    t.text     "post_prop47"
    t.text     "post_prop48"
    t.text     "post_prop49"
    t.text     "post_prop50"
    t.text     "post_prop51"
    t.text     "post_prop52"
    t.text     "post_prop53"
    t.text     "post_prop54"
    t.text     "post_prop55"
    t.text     "post_prop56"
    t.text     "post_prop57"
    t.text     "post_prop58"
    t.text     "post_prop59"
    t.text     "post_prop60"
    t.text     "post_prop61"
    t.text     "post_prop62"
    t.text     "post_prop63"
    t.text     "post_prop64"
    t.text     "post_prop65"
    t.text     "post_prop66"
    t.text     "post_prop67"
    t.text     "post_prop68"
    t.text     "post_prop69"
    t.text     "post_prop70"
    t.text     "post_prop71"
    t.text     "post_prop72"
    t.text     "post_prop73"
    t.text     "post_prop74"
    t.text     "post_prop75"
    t.text     "post_purchaseid"
    t.text     "post_referrer"
    t.text     "post_search_engine"
    t.text     "post_state"
    t.string   "post_visid_high",        limit: 25
    t.string   "post_visid_low",         limit: 25
    t.text     "post_zip"
    t.text     "prev_page"
    t.text     "ref_domain"
    t.text     "ref_type"
    t.text     "resolution"
    t.text     "service"
    t.text     "user_agent"
    t.text     "visit_keywords"
    t.text     "visit_num"
    t.text     "visit_page_num"
    t.text     "visit_referrer"
    t.text     "visit_search_engine"
    t.text     "visit_start_pagename"
    t.text     "visit_start_page_url"
    t.datetime "visit_start_time_gmt"
    t.datetime "created_at",                        null: false
    t.datetime "updated_at",                        null: false
    t.string   "visitor_id",             limit: 50
    t.string   "source",                 limit: 25
    t.string   "browser_height",         limit: 25
    t.string   "browser_width",          limit: 25
    t.string   "campaign",               limit: 50
    t.string   "c_color",                limit: 50
    t.string   "channel",                limit: 50
    t.string   "click_action",           limit: 50
    t.string   "click_action_type",      limit: 50
    t.string   "click_context",          limit: 50
    t.string   "click_context_type",     limit: 50
    t.string   "click_sourceid",         limit: 50
    t.string   "click_tag",              limit: 50
    t.string   "color",                  limit: 50
    t.string   "cookies",                limit: 50
    t.string   "ct_connect_type",        limit: 50
    t.string   "currency",               limit: 50
    t.string   "curr_factor",            limit: 50
    t.string   "curr_rate",              limit: 50
    t.string   "cust_hit_time_gmt",      limit: 50
    t.string   "cust_visid",             limit: 50
    t.string   "daily_visitor",          limit: 50
    t.string   "duplicated_from",        limit: 50
    t.string   "duplicate_events",       limit: 50
    t.string   "duplicate_purchase",     limit: 50
    t.string   "event_list",             limit: 50
    t.string   "hier1",                  limit: 50
    t.string   "hier2",                  limit: 50
    t.string   "hier3",                  limit: 50
    t.string   "hier4",                  limit: 50
    t.string   "hier5",                  limit: 50
    t.string   "hitid_high",             limit: 50
    t.string   "hitid_low",              limit: 50
    t.string   "hit_source",             limit: 50
    t.string   "hit_time_gmt",           limit: 50
    t.string   "homepage",               limit: 50
    t.string   "hourly_visitor",         limit: 50
    t.string   "ip2",                    limit: 50
    t.string   "java_enabled",           limit: 50
    t.string   "j_jscript",              limit: 50
    t.string   "mobile_id",              limit: 50
    t.string   "monthly_visitor",        limit: 50
    t.string   "mvvar1",                 limit: 50
    t.string   "mvvar2",                 limit: 50
    t.string   "mvvar3",                 limit: 50
    t.string   "namespace",              limit: 50
    t.string   "page_event",             limit: 50
    t.string   "page_event_var1",        limit: 50
    t.string   "page_event_var2",        limit: 50
    t.string   "page_event_var3",        limit: 50
    t.string   "pagename",               limit: 50
    t.string   "page_type",              limit: 50
    t.string   "paid_search",            limit: 50
    t.string   "partner_plugins",        limit: 50
    t.string   "persistent_cookie",      limit: 50
    t.string   "plugins",                limit: 50
    t.string   "post_cust_visid",        limit: 50
    t.string   "post_java_enabled",      limit: 50
    t.string   "post_mvvar1",            limit: 50
    t.string   "post_mvvar2",            limit: 50
    t.string   "post_mvvar3",            limit: 50
    t.string   "post_survey",            limit: 50
    t.string   "post_tnt",               limit: 50
    t.string   "post_transactionid",     limit: 50
    t.string   "post_t_time_info",       limit: 50
    t.string   "post_visid_type",        limit: 50
    t.string   "p_plugins",              limit: 50
    t.string   "product_list",           limit: 50
    t.string   "product_merchandising",  limit: 50
    t.string   "prop1"
    t.string   "prop2"
    t.string   "prop3"
    t.string   "prop4"
    t.string   "prop5"
    t.string   "prop6"
    t.string   "prop7"
    t.string   "prop8"
    t.string   "prop9"
    t.string   "prop10"
    t.string   "prop11"
    t.string   "prop12"
    t.string   "prop13"
    t.string   "prop14"
    t.string   "prop15"
    t.string   "prop16"
    t.string   "prop17"
    t.string   "prop18"
    t.string   "prop19"
    t.string   "prop20"
    t.string   "prop21"
    t.string   "prop22"
    t.string   "prop23"
    t.string   "prop24"
    t.string   "prop25"
    t.string   "prop26"
    t.string   "prop27"
    t.string   "prop28"
    t.string   "prop29"
    t.string   "prop30"
    t.string   "prop31"
    t.string   "prop32"
    t.string   "prop33"
    t.string   "prop34"
    t.string   "prop35"
    t.string   "prop36"
    t.string   "prop37"
    t.string   "prop38"
    t.string   "prop39"
    t.string   "prop40"
    t.string   "prop41"
    t.string   "prop42"
    t.string   "prop43"
    t.string   "prop44"
    t.string   "prop45"
    t.string   "prop46"
    t.string   "prop47"
    t.string   "prop48"
    t.string   "prop49"
    t.string   "prop50"
    t.string   "prop51"
    t.string   "prop52"
    t.string   "prop53"
    t.string   "prop54"
    t.string   "prop55"
    t.string   "prop56"
    t.string   "prop57"
    t.string   "prop58"
    t.string   "prop59"
    t.string   "prop60"
    t.string   "prop61"
    t.string   "prop62"
    t.string   "prop63"
    t.string   "prop64"
    t.string   "prop65"
    t.string   "prop66"
    t.string   "prop67"
    t.string   "prop68"
    t.string   "prop69"
    t.string   "prop70"
    t.string   "prop71"
    t.string   "prop72"
    t.string   "prop73"
    t.string   "prop74"
    t.string   "prop75"
    t.string   "purchaseid",             limit: 50
    t.string   "quarterly_visitor",      limit: 50
    t.string   "referrer",               limit: 50
    t.string   "sampled_hit",            limit: 50
    t.string   "search_engine",          limit: 50
    t.string   "search_page_num",        limit: 50
    t.string   "secondary_hit",          limit: 50
    t.string   "sourceid",               limit: 50
    t.string   "s_resolution",           limit: 50
    t.string   "state",                  limit: 50
    t.string   "stats_server",           limit: 50
    t.string   "tnt",                    limit: 50
    t.string   "tnt_post_vista",         limit: 50
    t.string   "transactionid",          limit: 50
    t.string   "truncated_hit",          limit: 50
    t.string   "t_time_info",            limit: 50
    t.string   "ua_color",               limit: 50
    t.string   "ua_os",                  limit: 50
    t.string   "ua_pixels",              limit: 50
    t.string   "user_hash",              limit: 50
    t.string   "userid",                 limit: 50
    t.string   "username",               limit: 50
    t.string   "user_server",            limit: 50
    t.string   "va_closer_detail",       limit: 50
    t.string   "va_closer_id",           limit: 50
    t.string   "va_finder_detail",       limit: 50
    t.string   "va_finder_id",           limit: 50
    t.string   "va_instance_event",      limit: 50
    t.string   "va_new_engagement",      limit: 50
    t.string   "visid_high",             limit: 50
    t.string   "visid_low",              limit: 50
    t.string   "visid_new",              limit: 50
    t.string   "visid_timestamp",        limit: 50
    t.string   "visid_type",             limit: 50
    t.string   "weekly_visitor",         limit: 50
    t.string   "yearly_visitor",         limit: 50
    t.string   "zip",                    limit: 50
  end

  add_index "datafeeds_2", ["id"], name: "primary_id", using: :btree
  add_index "datafeeds_2", ["post_visid_high", "post_visid_low"], name: "visitor_id", using: :btree
  add_index "datafeeds_2", ["visitor_id"], name: "visitor_id_field", using: :btree

  create_table "df_20130410", force: true do |t|
    t.text     "accept_language"
    t.text     "browser"
    t.text     "connection_type"
    t.text     "country"
    t.datetime "date_time"
    t.text     "domain"
    t.text     "evar1"
    t.text     "evar2"
    t.text     "evar3"
    t.text     "evar4"
    t.text     "evar5"
    t.text     "evar6"
    t.text     "evar7"
    t.text     "evar8"
    t.text     "evar9"
    t.text     "evar10"
    t.text     "evar11"
    t.text     "evar12"
    t.text     "evar13"
    t.text     "evar14"
    t.text     "evar15"
    t.text     "evar16"
    t.text     "evar17"
    t.text     "evar18"
    t.text     "evar19"
    t.text     "evar20"
    t.text     "evar21"
    t.text     "evar22"
    t.text     "evar23"
    t.text     "evar24"
    t.text     "evar25"
    t.text     "evar26"
    t.text     "evar27"
    t.text     "evar28"
    t.text     "evar29"
    t.text     "evar30"
    t.text     "evar31"
    t.text     "evar32"
    t.text     "evar33"
    t.text     "evar34"
    t.text     "evar35"
    t.text     "evar36"
    t.text     "evar37"
    t.text     "evar38"
    t.text     "evar39"
    t.text     "evar40"
    t.text     "evar41"
    t.text     "evar42"
    t.text     "evar43"
    t.text     "evar44"
    t.text     "evar45"
    t.text     "evar46"
    t.text     "evar47"
    t.text     "evar48"
    t.text     "evar49"
    t.text     "evar50"
    t.text     "evar51"
    t.text     "evar52"
    t.text     "evar53"
    t.text     "evar54"
    t.text     "evar55"
    t.text     "evar56"
    t.text     "evar57"
    t.text     "evar58"
    t.text     "evar59"
    t.text     "evar60"
    t.text     "evar61"
    t.text     "evar62"
    t.text     "evar63"
    t.text     "evar64"
    t.text     "evar65"
    t.text     "evar66"
    t.text     "evar67"
    t.text     "evar68"
    t.text     "evar69"
    t.text     "evar70"
    t.text     "evar71"
    t.text     "evar72"
    t.text     "evar73"
    t.text     "evar74"
    t.text     "evar75"
    t.text     "exclude_hit"
    t.text     "first_hit_pagename"
    t.text     "first_hit_page_url"
    t.text     "first_hit_referrer"
    t.datetime "first_hit_time_gmt"
    t.text     "geo_city"
    t.text     "geo_country"
    t.text     "geo_dma"
    t.text     "geo_region"
    t.text     "geo_zip"
    t.text     "ip"
    t.text     "javascript"
    t.text     "language"
    t.datetime "last_hit_time_gmt"
    t.text     "last_purchase_num"
    t.text     "last_purchase_time_gmt"
    t.text     "new_visit"
    t.text     "os"
    t.text     "post_browser_height"
    t.text     "post_browser_width"
    t.text     "post_campaign"
    t.text     "post_channel"
    t.text     "post_cookies"
    t.text     "post_currency"
    t.datetime "post_cust_hit_time_gmt"
    t.text     "post_evar1"
    t.text     "post_evar2"
    t.text     "post_evar3"
    t.text     "post_evar4"
    t.text     "post_evar5"
    t.text     "post_evar6"
    t.text     "post_evar7"
    t.text     "post_evar8"
    t.text     "post_evar9"
    t.text     "post_evar10"
    t.text     "post_evar11"
    t.text     "post_evar12"
    t.text     "post_evar13"
    t.text     "post_evar14"
    t.text     "post_evar15"
    t.text     "post_evar16"
    t.text     "post_evar17"
    t.text     "post_evar18"
    t.text     "post_evar19"
    t.text     "post_evar20"
    t.text     "post_evar21"
    t.text     "post_evar22"
    t.text     "post_evar23"
    t.text     "post_evar24"
    t.text     "post_evar25"
    t.text     "post_evar26"
    t.text     "post_evar27"
    t.text     "post_evar28"
    t.text     "post_evar29"
    t.text     "post_evar30"
    t.text     "post_evar31"
    t.text     "post_evar32"
    t.text     "post_evar33"
    t.text     "post_evar34"
    t.text     "post_evar35"
    t.text     "post_evar36"
    t.text     "post_evar37"
    t.text     "post_evar38"
    t.text     "post_evar39"
    t.text     "post_evar40"
    t.text     "post_evar41"
    t.text     "post_evar42"
    t.text     "post_evar43"
    t.text     "post_evar44"
    t.text     "post_evar45"
    t.text     "post_evar46"
    t.text     "post_evar47"
    t.text     "post_evar48"
    t.text     "post_evar49"
    t.text     "post_evar50"
    t.text     "post_evar51"
    t.text     "post_evar52"
    t.text     "post_evar53"
    t.text     "post_evar54"
    t.text     "post_evar55"
    t.text     "post_evar56"
    t.text     "post_evar57"
    t.text     "post_evar58"
    t.text     "post_evar59"
    t.text     "post_evar60"
    t.text     "post_evar61"
    t.text     "post_evar62"
    t.text     "post_evar63"
    t.text     "post_evar64"
    t.text     "post_evar65"
    t.text     "post_evar66"
    t.text     "post_evar67"
    t.text     "post_evar68"
    t.text     "post_evar69"
    t.text     "post_evar70"
    t.text     "post_evar71"
    t.text     "post_evar72"
    t.text     "post_evar73"
    t.text     "post_evar74"
    t.text     "post_evar75"
    t.text     "post_event_list"
    t.text     "post_hier1"
    t.text     "post_hier2"
    t.text     "post_hier3"
    t.text     "post_hier4"
    t.text     "post_hier5"
    t.text     "post_keywords"
    t.text     "post_page_event"
    t.text     "post_page_event_var1"
    t.text     "post_page_event_var2"
    t.text     "post_page_event_var3"
    t.text     "post_pagename"
    t.text     "post_pagename_no_url"
    t.text     "post_page_type"
    t.text     "post_page_url"
    t.text     "post_persistent_cookie"
    t.text     "post_product_list"
    t.text     "post_prop1"
    t.text     "post_prop2"
    t.text     "post_prop3"
    t.text     "post_prop4"
    t.text     "post_prop5"
    t.text     "post_prop6"
    t.text     "post_prop7"
    t.text     "post_prop8"
    t.text     "post_prop9"
    t.text     "post_prop10"
    t.text     "post_prop11"
    t.text     "post_prop12"
    t.text     "post_prop13"
    t.text     "post_prop14"
    t.text     "post_prop15"
    t.text     "post_prop16"
    t.text     "post_prop17"
    t.text     "post_prop18"
    t.text     "post_prop19"
    t.text     "post_prop20"
    t.text     "post_prop21"
    t.text     "post_prop22"
    t.text     "post_prop23"
    t.text     "post_prop24"
    t.text     "post_prop25"
    t.text     "post_prop26"
    t.text     "post_prop27"
    t.text     "post_prop28"
    t.text     "post_prop29"
    t.text     "post_prop30"
    t.text     "post_prop31"
    t.text     "post_prop32"
    t.text     "post_prop33"
    t.text     "post_prop34"
    t.text     "post_prop35"
    t.text     "post_prop36"
    t.text     "post_prop37"
    t.text     "post_prop38"
    t.text     "post_prop39"
    t.text     "post_prop40"
    t.text     "post_prop41"
    t.text     "post_prop42"
    t.text     "post_prop43"
    t.text     "post_prop44"
    t.text     "post_prop45"
    t.text     "post_prop46"
    t.text     "post_prop47"
    t.text     "post_prop48"
    t.text     "post_prop49"
    t.text     "post_prop50"
    t.text     "post_prop51"
    t.text     "post_prop52"
    t.text     "post_prop53"
    t.text     "post_prop54"
    t.text     "post_prop55"
    t.text     "post_prop56"
    t.text     "post_prop57"
    t.text     "post_prop58"
    t.text     "post_prop59"
    t.text     "post_prop60"
    t.text     "post_prop61"
    t.text     "post_prop62"
    t.text     "post_prop63"
    t.text     "post_prop64"
    t.text     "post_prop65"
    t.text     "post_prop66"
    t.text     "post_prop67"
    t.text     "post_prop68"
    t.text     "post_prop69"
    t.text     "post_prop70"
    t.text     "post_prop71"
    t.text     "post_prop72"
    t.text     "post_prop73"
    t.text     "post_prop74"
    t.text     "post_prop75"
    t.text     "post_purchaseid"
    t.text     "post_referrer"
    t.text     "post_search_engine"
    t.text     "post_state"
    t.string   "post_visid_high",        limit: 25
    t.string   "post_visid_low",         limit: 25
    t.text     "post_zip"
    t.text     "prev_page"
    t.text     "ref_domain"
    t.text     "ref_type"
    t.text     "resolution"
    t.text     "service"
    t.text     "user_agent"
    t.text     "visit_keywords"
    t.text     "visit_num"
    t.text     "visit_page_num"
    t.text     "visit_referrer"
    t.text     "visit_search_engine"
    t.text     "visit_start_pagename"
    t.text     "visit_start_page_url"
    t.datetime "visit_start_time_gmt"
    t.datetime "created_at",                        null: false
    t.datetime "updated_at",                        null: false
    t.string   "visitor_id",             limit: 50
    t.string   "source",                 limit: 25
  end

  add_index "df_20130410", ["id"], name: "primary_id", using: :btree
  add_index "df_20130410", ["post_visid_high", "post_visid_low"], name: "visitor_id", using: :btree
  add_index "df_20130410", ["visitor_id"], name: "visitor_id_field", using: :btree

  create_table "df_20130612", force: true do |t|
    t.text     "accept_language"
    t.text     "browser"
    t.text     "connection_type"
    t.text     "country"
    t.datetime "date_time"
    t.text     "domain"
    t.text     "evar1"
    t.text     "evar2"
    t.text     "evar3"
    t.text     "evar4"
    t.text     "evar5"
    t.text     "evar6"
    t.text     "evar7"
    t.text     "evar8"
    t.text     "evar9"
    t.text     "evar10"
    t.text     "evar11"
    t.text     "evar12"
    t.text     "evar13"
    t.text     "evar14"
    t.text     "evar15"
    t.text     "evar16"
    t.text     "evar17"
    t.text     "evar18"
    t.text     "evar19"
    t.text     "evar20"
    t.text     "evar21"
    t.text     "evar22"
    t.text     "evar23"
    t.text     "evar24"
    t.text     "evar25"
    t.text     "evar26"
    t.text     "evar27"
    t.text     "evar28"
    t.text     "evar29"
    t.text     "evar30"
    t.text     "evar31"
    t.text     "evar32"
    t.text     "evar33"
    t.text     "evar34"
    t.text     "evar35"
    t.text     "evar36"
    t.text     "evar37"
    t.text     "evar38"
    t.text     "evar39"
    t.text     "evar40"
    t.text     "evar41"
    t.text     "evar42"
    t.text     "evar43"
    t.text     "evar44"
    t.text     "evar45"
    t.text     "evar46"
    t.text     "evar47"
    t.text     "evar48"
    t.text     "evar49"
    t.text     "evar50"
    t.text     "evar51"
    t.text     "evar52"
    t.text     "evar53"
    t.text     "evar54"
    t.text     "evar55"
    t.text     "evar56"
    t.text     "evar57"
    t.text     "evar58"
    t.text     "evar59"
    t.text     "evar60"
    t.text     "evar61"
    t.text     "evar62"
    t.text     "evar63"
    t.text     "evar64"
    t.text     "evar65"
    t.text     "evar66"
    t.text     "evar67"
    t.text     "evar68"
    t.text     "evar69"
    t.text     "evar70"
    t.text     "evar71"
    t.text     "evar72"
    t.text     "evar73"
    t.text     "evar74"
    t.text     "evar75"
    t.text     "exclude_hit"
    t.text     "first_hit_pagename"
    t.text     "first_hit_page_url"
    t.text     "first_hit_referrer"
    t.datetime "first_hit_time_gmt"
    t.text     "geo_city"
    t.text     "geo_country"
    t.text     "geo_dma"
    t.text     "geo_region"
    t.text     "geo_zip"
    t.text     "ip"
    t.text     "javascript"
    t.text     "language"
    t.datetime "last_hit_time_gmt"
    t.text     "last_purchase_num"
    t.text     "last_purchase_time_gmt"
    t.text     "new_visit"
    t.text     "os"
    t.text     "post_browser_height"
    t.text     "post_browser_width"
    t.text     "post_campaign"
    t.text     "post_channel"
    t.text     "post_cookies"
    t.text     "post_currency"
    t.datetime "post_cust_hit_time_gmt"
    t.text     "post_evar1"
    t.text     "post_evar2"
    t.text     "post_evar3"
    t.text     "post_evar4"
    t.text     "post_evar5"
    t.text     "post_evar6"
    t.text     "post_evar7"
    t.text     "post_evar8"
    t.text     "post_evar9"
    t.text     "post_evar10"
    t.text     "post_evar11"
    t.text     "post_evar12"
    t.text     "post_evar13"
    t.text     "post_evar14"
    t.text     "post_evar15"
    t.text     "post_evar16"
    t.text     "post_evar17"
    t.text     "post_evar18"
    t.text     "post_evar19"
    t.text     "post_evar20"
    t.text     "post_evar21"
    t.text     "post_evar22"
    t.text     "post_evar23"
    t.text     "post_evar24"
    t.text     "post_evar25"
    t.text     "post_evar26"
    t.text     "post_evar27"
    t.text     "post_evar28"
    t.text     "post_evar29"
    t.text     "post_evar30"
    t.text     "post_evar31"
    t.text     "post_evar32"
    t.text     "post_evar33"
    t.text     "post_evar34"
    t.text     "post_evar35"
    t.text     "post_evar36"
    t.text     "post_evar37"
    t.text     "post_evar38"
    t.text     "post_evar39"
    t.text     "post_evar40"
    t.text     "post_evar41"
    t.text     "post_evar42"
    t.text     "post_evar43"
    t.text     "post_evar44"
    t.text     "post_evar45"
    t.text     "post_evar46"
    t.text     "post_evar47"
    t.text     "post_evar48"
    t.text     "post_evar49"
    t.text     "post_evar50"
    t.text     "post_evar51"
    t.text     "post_evar52"
    t.text     "post_evar53"
    t.text     "post_evar54"
    t.text     "post_evar55"
    t.text     "post_evar56"
    t.text     "post_evar57"
    t.text     "post_evar58"
    t.text     "post_evar59"
    t.text     "post_evar60"
    t.text     "post_evar61"
    t.text     "post_evar62"
    t.text     "post_evar63"
    t.text     "post_evar64"
    t.text     "post_evar65"
    t.text     "post_evar66"
    t.text     "post_evar67"
    t.text     "post_evar68"
    t.text     "post_evar69"
    t.text     "post_evar70"
    t.text     "post_evar71"
    t.text     "post_evar72"
    t.text     "post_evar73"
    t.text     "post_evar74"
    t.text     "post_evar75"
    t.text     "post_event_list"
    t.text     "post_hier1"
    t.text     "post_hier2"
    t.text     "post_hier3"
    t.text     "post_hier4"
    t.text     "post_hier5"
    t.text     "post_keywords"
    t.text     "post_page_event"
    t.text     "post_page_event_var1"
    t.text     "post_page_event_var2"
    t.text     "post_page_event_var3"
    t.text     "post_pagename"
    t.text     "post_pagename_no_url"
    t.text     "post_page_type"
    t.text     "post_page_url"
    t.text     "post_persistent_cookie"
    t.text     "post_product_list"
    t.text     "post_prop1"
    t.text     "post_prop2"
    t.text     "post_prop3"
    t.text     "post_prop4"
    t.text     "post_prop5"
    t.text     "post_prop6"
    t.text     "post_prop7"
    t.text     "post_prop8"
    t.text     "post_prop9"
    t.text     "post_prop10"
    t.text     "post_prop11"
    t.text     "post_prop12"
    t.text     "post_prop13"
    t.text     "post_prop14"
    t.text     "post_prop15"
    t.text     "post_prop16"
    t.text     "post_prop17"
    t.text     "post_prop18"
    t.text     "post_prop19"
    t.text     "post_prop20"
    t.text     "post_prop21"
    t.text     "post_prop22"
    t.text     "post_prop23"
    t.text     "post_prop24"
    t.text     "post_prop25"
    t.text     "post_prop26"
    t.text     "post_prop27"
    t.text     "post_prop28"
    t.text     "post_prop29"
    t.text     "post_prop30"
    t.text     "post_prop31"
    t.text     "post_prop32"
    t.text     "post_prop33"
    t.text     "post_prop34"
    t.text     "post_prop35"
    t.text     "post_prop36"
    t.text     "post_prop37"
    t.text     "post_prop38"
    t.text     "post_prop39"
    t.text     "post_prop40"
    t.text     "post_prop41"
    t.text     "post_prop42"
    t.text     "post_prop43"
    t.text     "post_prop44"
    t.text     "post_prop45"
    t.text     "post_prop46"
    t.text     "post_prop47"
    t.text     "post_prop48"
    t.text     "post_prop49"
    t.text     "post_prop50"
    t.text     "post_prop51"
    t.text     "post_prop52"
    t.text     "post_prop53"
    t.text     "post_prop54"
    t.text     "post_prop55"
    t.text     "post_prop56"
    t.text     "post_prop57"
    t.text     "post_prop58"
    t.text     "post_prop59"
    t.text     "post_prop60"
    t.text     "post_prop61"
    t.text     "post_prop62"
    t.text     "post_prop63"
    t.text     "post_prop64"
    t.text     "post_prop65"
    t.text     "post_prop66"
    t.text     "post_prop67"
    t.text     "post_prop68"
    t.text     "post_prop69"
    t.text     "post_prop70"
    t.text     "post_prop71"
    t.text     "post_prop72"
    t.text     "post_prop73"
    t.text     "post_prop74"
    t.text     "post_prop75"
    t.text     "post_purchaseid"
    t.text     "post_referrer"
    t.text     "post_search_engine"
    t.text     "post_state"
    t.string   "post_visid_high",        limit: 25
    t.string   "post_visid_low",         limit: 25
    t.text     "post_zip"
    t.text     "prev_page"
    t.text     "ref_domain"
    t.text     "ref_type"
    t.text     "resolution"
    t.text     "service"
    t.text     "user_agent"
    t.text     "visit_keywords"
    t.text     "visit_num"
    t.text     "visit_page_num"
    t.text     "visit_referrer"
    t.text     "visit_search_engine"
    t.text     "visit_start_pagename"
    t.text     "visit_start_page_url"
    t.datetime "visit_start_time_gmt"
    t.datetime "created_at",                        null: false
    t.datetime "updated_at",                        null: false
    t.string   "visitor_id",             limit: 50
    t.string   "source",                 limit: 25
  end

  add_index "df_20130612", ["id"], name: "primary_id", using: :btree
  add_index "df_20130612", ["post_visid_high", "post_visid_low"], name: "visitor_id", using: :btree
  add_index "df_20130612", ["visitor_id"], name: "visitor_id_field", using: :btree

  create_table "hit_data", id: false, force: true do |t|
    t.integer  "hit_time_gmt",           limit: 8
    t.string   "service",                limit: 2
    t.string   "accept_language",        limit: 20
    t.datetime "date_time"
    t.decimal  "visid_high",                         precision: 20, scale: 0
    t.decimal  "visid_low",                          precision: 20, scale: 0
    t.text     "event_list"
    t.string   "homepage",               limit: 1
    t.string   "ip",                     limit: 20
    t.integer  "page_event",             limit: 8
    t.string   "page_event_var1"
    t.string   "page_event_var2",        limit: 100
    t.string   "page_type",              limit: 100
    t.string   "page_url"
    t.string   "pagename",               limit: 100
    t.text     "product_list"
    t.string   "user_server",            limit: 100
    t.string   "channel",                limit: 100
    t.string   "prop1",                  limit: 100
    t.string   "prop2",                  limit: 100
    t.string   "prop3",                  limit: 100
    t.string   "prop4",                  limit: 100
    t.string   "prop5",                  limit: 100
    t.string   "prop6",                  limit: 100
    t.string   "prop7",                  limit: 100
    t.string   "prop8",                  limit: 100
    t.string   "prop9",                  limit: 100
    t.string   "prop10",                 limit: 100
    t.string   "prop11",                 limit: 100
    t.string   "prop12",                 limit: 100
    t.string   "prop13",                 limit: 100
    t.string   "prop14",                 limit: 100
    t.string   "prop15",                 limit: 100
    t.string   "prop16",                 limit: 100
    t.string   "prop17",                 limit: 100
    t.string   "prop18",                 limit: 100
    t.string   "prop19",                 limit: 100
    t.string   "prop20",                 limit: 100
    t.string   "prop21",                 limit: 100
    t.string   "prop22",                 limit: 100
    t.string   "prop23",                 limit: 100
    t.string   "prop24",                 limit: 100
    t.string   "prop25",                 limit: 100
    t.string   "prop26",                 limit: 100
    t.string   "prop27",                 limit: 100
    t.string   "prop28",                 limit: 100
    t.string   "prop29",                 limit: 100
    t.string   "prop30",                 limit: 100
    t.string   "prop31",                 limit: 100
    t.string   "prop32",                 limit: 100
    t.string   "prop33"
    t.string   "prop34",                 limit: 100
    t.string   "prop35",                 limit: 100
    t.string   "prop36",                 limit: 100
    t.string   "prop37",                 limit: 100
    t.string   "prop38",                 limit: 100
    t.string   "prop39",                 limit: 100
    t.string   "prop40",                 limit: 100
    t.string   "prop41",                 limit: 100
    t.string   "prop42",                 limit: 100
    t.string   "prop43",                 limit: 100
    t.string   "prop44",                 limit: 100
    t.string   "prop45",                 limit: 100
    t.string   "prop46",                 limit: 100
    t.string   "prop47",                 limit: 100
    t.string   "prop48",                 limit: 100
    t.string   "prop49",                 limit: 100
    t.string   "prop50",                 limit: 100
    t.string   "purchaseID",             limit: 20
    t.string   "referrer"
    t.string   "state",                  limit: 50
    t.text     "user_agent"
    t.string   "zip",                    limit: 50
    t.integer  "search_engine",          limit: 8
    t.integer  "exclude_hit",            limit: 8
    t.string   "hier1"
    t.string   "hier2"
    t.string   "hier3"
    t.string   "hier4"
    t.string   "hier5"
    t.integer  "browser",                limit: 8
    t.integer  "post_browser_height",    limit: 8
    t.integer  "post_browser_width",     limit: 8
    t.string   "post_cookies",           limit: 1
    t.string   "post_jave_enabled",      limit: 1
    t.string   "post_persistent_cookie", limit: 1
    t.integer  "color",                  limit: 8
    t.integer  "connection_type",        limit: 8
    t.integer  "country",                limit: 8
    t.string   "domain",                 limit: 100
    t.string   "post_t_time_info",       limit: 100
    t.integer  "javascript",             limit: 8
    t.integer  "language",               limit: 8
    t.integer  "os",                     limit: 8
    t.string   "plugins",                limit: 180
    t.integer  "resolution",             limit: 8
    t.integer  "last_hit_time_gmt",      limit: 8
    t.integer  "first_hit_time_gmt",     limit: 8
    t.integer  "visit_start_time_gmt",   limit: 8
    t.integer  "last_purchase_time_gmt", limit: 8
    t.integer  "last_purchase_num",      limit: 8
    t.string   "first_hit_page_url"
    t.string   "first_hit_pagename",     limit: 100
    t.string   "visit_start_page_url"
    t.string   "visit_start_pagename",   limit: 100
    t.string   "first_hit_referrer"
    t.string   "visit_referrer"
    t.integer  "visit_search_engine",    limit: 8
    t.integer  "visit_num",              limit: 8
    t.integer  "visit_page_num",         limit: 8
    t.integer  "prev_page",              limit: 8
    t.string   "geo_city",               limit: 32
    t.string   "geo_country",            limit: 4
    t.string   "geo_region",             limit: 32
    t.integer  "duplicate_purchase",     limit: 8
    t.integer  "new_visit",              limit: 8
    t.integer  "daily_visitor",          limit: 8
    t.integer  "hourly_visitor",         limit: 8
    t.integer  "monthly_visitor",        limit: 8
    t.integer  "yearly_visitor",         limit: 8
    t.string   "post_campaign"
    t.string   "evar1"
    t.string   "evar2"
    t.string   "evar3"
    t.string   "evar4"
    t.string   "evar5"
    t.string   "evar6"
    t.string   "evar7"
    t.string   "evar8"
    t.string   "evar9"
    t.string   "evar10"
    t.string   "evar11"
    t.string   "evar12"
    t.string   "evar13"
    t.string   "evar14"
    t.string   "evar15"
    t.string   "evar16"
    t.string   "evar17"
    t.string   "evar18"
    t.string   "evar19"
    t.string   "evar20"
    t.string   "evar21"
    t.string   "evar22"
    t.string   "evar23"
    t.string   "evar24"
    t.string   "evar25"
    t.string   "evar26"
    t.string   "evar27"
    t.string   "evar28"
    t.string   "evar29"
    t.string   "evar30"
    t.string   "evar31"
    t.string   "evar32"
    t.string   "evar33"
    t.string   "evar34"
    t.string   "evar35"
    t.string   "evar36"
    t.string   "evar37"
    t.string   "evar38"
    t.string   "evar39"
    t.string   "evar40"
    t.string   "evar41"
    t.string   "evar42"
    t.string   "evar43"
    t.string   "evar44"
    t.string   "evar45"
    t.string   "evar46"
    t.string   "evar47"
    t.string   "evar48"
    t.string   "evar49"
    t.string   "evar50"
    t.string   "post_evar1"
    t.string   "post_evar2"
    t.string   "post_evar3"
    t.string   "post_evar4"
    t.string   "post_evar5"
    t.text     "post_evar6",             limit: 255
    t.string   "post_evar7"
    t.text     "post_evar8",             limit: 255
    t.text     "post_evar9",             limit: 255
    t.text     "post_evar10",            limit: 255
    t.text     "post_evar11",            limit: 255
    t.text     "post_evar12",            limit: 255
    t.string   "post_evar13"
    t.text     "post_evar14",            limit: 255
    t.string   "post_evar15"
    t.text     "post_evar16",            limit: 255
    t.text     "post_evar17",            limit: 255
    t.text     "post_evar18",            limit: 255
    t.text     "post_evar19",            limit: 255
    t.text     "post_evar20",            limit: 255
    t.text     "post_evar21",            limit: 255
    t.text     "post_evar22",            limit: 255
    t.text     "post_evar23",            limit: 255
    t.text     "post_evar24",            limit: 255
    t.text     "post_evar25",            limit: 255
    t.text     "post_evar26",            limit: 255
    t.text     "post_evar27",            limit: 255
    t.text     "post_evar28",            limit: 255
    t.text     "post_evar29",            limit: 255
    t.text     "post_evar30",            limit: 255
    t.text     "post_evar31",            limit: 255
    t.text     "post_evar32",            limit: 255
    t.text     "post_evar33",            limit: 255
    t.text     "post_evar34",            limit: 255
    t.text     "post_evar35",            limit: 255
    t.text     "post_evar36",            limit: 255
    t.text     "post_evar37",            limit: 255
    t.text     "post_evar38",            limit: 255
    t.text     "post_evar39",            limit: 255
    t.text     "post_evar40",            limit: 255
    t.text     "post_evar41",            limit: 255
    t.text     "post_evar42",            limit: 255
    t.text     "post_evar43",            limit: 255
    t.text     "post_evar44",            limit: 255
    t.text     "post_evar45",            limit: 255
    t.text     "post_evar46",            limit: 255
    t.text     "post_evar47",            limit: 255
    t.text     "post_evar48",            limit: 255
    t.text     "post_evar49",            limit: 255
    t.text     "post_evar50",            limit: 255
    t.string   "click_action",           limit: 100
    t.integer  "click_action_type",      limit: 8
    t.string   "click_content"
    t.integer  "click_content_type",     limit: 8
    t.integer  "click_sourceid",         limit: 8
    t.string   "click_tag",              limit: 10
  end

  create_table "hit_data_20110812", id: false, force: true do |t|
    t.integer  "hit_time_gmt",           limit: 8
    t.string   "service",                limit: 2
    t.string   "accept_language",        limit: 20
    t.datetime "date_time"
    t.decimal  "visid_high",                         precision: 20, scale: 0
    t.decimal  "visid_low",                          precision: 20, scale: 0
    t.text     "event_list"
    t.string   "homepage",               limit: 1
    t.string   "ip",                     limit: 20
    t.integer  "page_event",             limit: 8
    t.string   "page_event_var1"
    t.string   "page_event_var2",        limit: 100
    t.string   "page_type",              limit: 100
    t.string   "page_url"
    t.string   "pagename",               limit: 100
    t.text     "product_list"
    t.string   "user_server",            limit: 100
    t.string   "channel",                limit: 100
    t.string   "prop1",                  limit: 100
    t.string   "prop2",                  limit: 100
    t.string   "prop3",                  limit: 100
    t.string   "prop4",                  limit: 100
    t.string   "prop5",                  limit: 100
    t.string   "prop6",                  limit: 100
    t.string   "prop7",                  limit: 100
    t.string   "prop8",                  limit: 100
    t.string   "prop9",                  limit: 100
    t.string   "prop10",                 limit: 100
    t.string   "prop11",                 limit: 100
    t.string   "prop12",                 limit: 100
    t.string   "prop13",                 limit: 100
    t.string   "prop14",                 limit: 100
    t.string   "prop15",                 limit: 100
    t.string   "prop16",                 limit: 100
    t.string   "prop17",                 limit: 100
    t.string   "prop18",                 limit: 100
    t.string   "prop19",                 limit: 100
    t.string   "prop20",                 limit: 100
    t.string   "prop21",                 limit: 100
    t.string   "prop22",                 limit: 100
    t.string   "prop23",                 limit: 100
    t.string   "prop24",                 limit: 100
    t.string   "prop25",                 limit: 100
    t.string   "prop26",                 limit: 100
    t.string   "prop27",                 limit: 100
    t.string   "prop28",                 limit: 100
    t.string   "prop29",                 limit: 100
    t.string   "prop30",                 limit: 100
    t.string   "prop31",                 limit: 100
    t.string   "prop32",                 limit: 100
    t.string   "prop33"
    t.string   "prop34",                 limit: 100
    t.string   "prop35",                 limit: 100
    t.string   "prop36",                 limit: 100
    t.string   "prop37",                 limit: 100
    t.string   "prop38",                 limit: 100
    t.string   "prop39",                 limit: 100
    t.string   "prop40",                 limit: 100
    t.string   "prop41",                 limit: 100
    t.string   "prop42",                 limit: 100
    t.string   "prop43",                 limit: 100
    t.string   "prop44",                 limit: 100
    t.string   "prop45",                 limit: 100
    t.string   "prop46",                 limit: 100
    t.string   "prop47",                 limit: 100
    t.string   "prop48",                 limit: 100
    t.string   "prop49",                 limit: 100
    t.string   "prop50",                 limit: 100
    t.string   "purchaseID",             limit: 20
    t.string   "referrer"
    t.string   "state",                  limit: 50
    t.text     "user_agent"
    t.string   "zip",                    limit: 50
    t.integer  "search_engine",          limit: 8
    t.integer  "exclude_hit",            limit: 8
    t.string   "hier1"
    t.string   "hier2"
    t.string   "hier3"
    t.string   "hier4"
    t.string   "hier5"
    t.integer  "browser",                limit: 8
    t.integer  "post_browser_height",    limit: 8
    t.integer  "post_browser_width",     limit: 8
    t.string   "post_cookies",           limit: 1
    t.string   "post_jave_enabled",      limit: 1
    t.string   "post_persistent_cookie", limit: 1
    t.integer  "color",                  limit: 8
    t.integer  "connection_type",        limit: 8
    t.integer  "country",                limit: 8
    t.string   "domain",                 limit: 100
    t.string   "post_t_time_info",       limit: 100
    t.integer  "javascript",             limit: 8
    t.integer  "language",               limit: 8
    t.integer  "os",                     limit: 8
    t.string   "plugins",                limit: 180
    t.integer  "resolution",             limit: 8
    t.integer  "last_hit_time_gmt",      limit: 8
    t.integer  "first_hit_time_gmt",     limit: 8
    t.integer  "visit_start_time_gmt",   limit: 8
    t.integer  "last_purchase_time_gmt", limit: 8
    t.integer  "last_purchase_num",      limit: 8
    t.string   "first_hit_page_url"
    t.string   "first_hit_pagename",     limit: 100
    t.string   "visit_start_page_url"
    t.string   "visit_start_pagename",   limit: 100
    t.string   "first_hit_referrer"
    t.string   "visit_referrer"
    t.integer  "visit_search_engine",    limit: 8
    t.integer  "visit_num",              limit: 8
    t.integer  "visit_page_num",         limit: 8
    t.integer  "prev_page",              limit: 8
    t.string   "geo_city",               limit: 32
    t.string   "geo_country",            limit: 4
    t.string   "geo_region",             limit: 32
    t.integer  "duplicate_purchase",     limit: 8
    t.integer  "new_visit",              limit: 8
    t.integer  "daily_visitor",          limit: 8
    t.integer  "hourly_visitor",         limit: 8
    t.integer  "monthly_visitor",        limit: 8
    t.integer  "yearly_visitor",         limit: 8
    t.string   "post_campaign"
    t.string   "evar1"
    t.string   "evar2"
    t.string   "evar3"
    t.string   "evar4"
    t.string   "evar5"
    t.string   "evar6"
    t.string   "evar7"
    t.string   "evar8"
    t.string   "evar9"
    t.string   "evar10"
    t.string   "evar11"
    t.string   "evar12"
    t.string   "evar13"
    t.string   "evar14"
    t.string   "evar15"
    t.string   "evar16"
    t.string   "evar17"
    t.string   "evar18"
    t.string   "evar19"
    t.string   "evar20"
    t.string   "evar21"
    t.string   "evar22"
    t.string   "evar23"
    t.string   "evar24"
    t.string   "evar25"
    t.string   "evar26"
    t.string   "evar27"
    t.string   "evar28"
    t.string   "evar29"
    t.string   "evar30"
    t.string   "evar31"
    t.string   "evar32"
    t.string   "evar33"
    t.string   "evar34"
    t.string   "evar35"
    t.string   "evar36"
    t.string   "evar37"
    t.string   "evar38"
    t.string   "evar39"
    t.string   "evar40"
    t.string   "evar41"
    t.string   "evar42"
    t.string   "evar43"
    t.string   "evar44"
    t.string   "evar45"
    t.string   "evar46"
    t.string   "evar47"
    t.string   "evar48"
    t.string   "evar49"
    t.string   "evar50"
    t.string   "post_evar1"
    t.string   "post_evar2"
    t.string   "post_evar3"
    t.string   "post_evar4"
    t.string   "post_evar5"
    t.string   "post_evar6"
    t.string   "post_evar7"
    t.string   "post_evar8"
    t.string   "post_evar9"
    t.string   "post_evar10"
    t.string   "post_evar11"
    t.string   "post_evar12"
    t.string   "post_evar13"
    t.string   "post_evar14"
    t.string   "post_evar15"
    t.string   "post_evar16"
    t.string   "post_evar17"
    t.string   "post_evar18"
    t.string   "post_evar19"
    t.string   "post_evar20"
    t.string   "post_evar21"
    t.string   "post_evar22"
    t.string   "post_evar23"
    t.string   "post_evar24"
    t.string   "post_evar25"
    t.string   "post_evar26"
    t.string   "post_evar27"
    t.string   "post_evar28"
    t.string   "post_evar29"
    t.string   "post_evar30"
    t.string   "post_evar31"
    t.string   "post_evar32"
    t.string   "post_evar33"
    t.string   "post_evar34"
    t.string   "post_evar35"
    t.string   "post_evar36"
    t.string   "post_evar37"
    t.string   "post_evar38"
    t.string   "post_evar39"
    t.string   "post_evar40"
    t.string   "post_evar41"
    t.string   "post_evar42"
    t.string   "post_evar43"
    t.string   "post_evar44"
    t.string   "post_evar45"
    t.string   "post_evar46"
    t.string   "post_evar47"
    t.string   "post_evar48"
    t.string   "post_evar49"
    t.string   "post_evar50"
    t.string   "click_action",           limit: 100
    t.integer  "click_action_type",      limit: 8
    t.string   "click_content"
    t.integer  "click_content_type",     limit: 8
    t.integer  "click_sourceid",         limit: 8
    t.string   "click_tag",              limit: 10
  end

end
